### ISSUE TITLE
Error in Swirl: Invalid tag for scalar: int#base60 (since yaml version 2.1.17)

### ISSUE THREAD

**Issue by nancyirisarri** [viking/r-yaml#53]
Hi,

While trying to follow on RStudio the Swirl lesson:

[https://github.com/swirldev/swirl_courses/tree/master/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr](https://github.com/swirldev/swirl_courses/tree/master/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr)

I get the following error:

`Error in yaml.load(readLines(con), error.label = error.label, ...) :`

`(C:/Users/...R/win-library/3.4/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Invalid tag for scalar: int#base60`

Occurs since yaml package version 2.1.17 on Windows and Mac OS. Any workarounds or solutions?

**Comment by viking** [comment]
Thanks for your report. I'll check it out.

**Comment by viking** [comment]
Got it fixed, thanks again for the report.

The YAML code that parses strings to guess what data type they are (integer, numeric, etc) tags things that look like a time (5:20) as a base-60 integer. Before version 2.1.17, these were passed through untouched. In 2.1.17, I changed `yaml.load` to throw an error for integers in a weird base. I had forgotten about the `int#base60` tag.

Sorry about that. It'll be fixed in the next release on CRAN. In the meantime you can use the devtools package to install the yaml package from Github (see https://github.com/viking/r-yaml#git-via-devtools).

**Comment by nancyirisarri** [comment]
Great, nice that you could fix it. 

This is for a course in Coursera and in the meantime asked people to use version 2.1.16. I advised people to keep an eye on updates to this package and will update the solution to let them know.

**Comment by jercob** [comment]
Hi 

I am getting an error while installing yam1. Could you help me here

> install.packages("yam1")
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘yam1’ is not available (for R version 3.4.4)

Thanks

**Comment by viking** [comment]
@jercob It looks like you've misspelled `yaml` as `yam1`. Try this instead: `install.packages("yaml")`

This is not the appropriate place to ask for help. Github issues is typically used for bug reports. In the future, I recommend posting on [Stack Overflow](https://stackoverflow.com) or the R help mailing list. See the following page for more information about getting help: https://www.r-project.org/help.html

**Comment by viking** [comment]
The fix for this has finally been released to CRAN in version 2.1.19. Sorry for the delay, there were some other issues I had to fix before releasing a new version.

**Comment by Rajeshanand** [comment]
Hi,
I'm getting this error message. 

Attempting to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  (C:/Users/Rajeshananand Seshan/Documents/R/win-library/3.4/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Invalid tag for scalar: int#base60

| Leaving swirl now. Type swirl() to resume.

**Comment by Rajeshanand** [comment]
Hi,
Can some help for the above request?

**Comment by viking** [comment]
@Rajeshanand As mentioned above in previous comments, the issue has been fixed and released in the latest version of the yaml package (version 2.1.19). Please install the updated version by running: `install.packages('yaml', repos="https://cran.r-project.org")`.

**Comment by FarmGeorge** [comment]
Still receiving this error October of 2022.

Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  : 
  (/Library/Frameworks/R.framework/Versions/4.2/Resources/library/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Scanner error: while scanning a tag at line 205, column 9 did not find expected whitespace or line break at line 205, column 19
In addition: Warning message:
`tbl_df()` was deprecated in dplyr 1.0.0.
ℹ Please use `tibble::as_tibble()` instead.
ℹ The deprecated feature was likely used in the swirl package.
  Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated.

**Comment by spgarbet** [comment]
I've picked up maintenance on this package. Can you provide a short bit of code that reproduces the error?

**Comment by spgarbet** [comment]
Looking at the source lesson I think that is malformed yaml. It''s got a string starting with a "!"which denotes a tag reference, then it follows with text. If the text was enclosed in a quote of some form it would be fine. That swirl example hasn't been touched in a good number of years it looks like.

**Comment by spgarbet** [comment]
Also, the error is not related to the base#60 issue.

**Comment by FarmGeorge** [comment]
Thank you for following up, do you have a suggestion for a better place to address the error? 
Below is the code that led to the error. 

packageVersion("swirl")
[1] ‘2.4.5’


>library(swirl)
>install_from_swirl("Getting and Cleaning Data")
>swirl()

1: Getting and Cleaning Data
2: Take me to the swirl course repository!

Selection: 1
| Please choose a lesson, or type 0 to return to course menu.

1: Manipulating Data with dplyr
2: Grouping and Chaining with dplyr
3: Tidying Data with tidyr
4: Dates and Times with lubridate

Selection: 1

| Attempting to load lesson dependencies...
| Package ‘dplyr’ loaded correctly!

**Comment by spgarbet** [comment]
I could send a pull request to swirl. It's a trivial fix.
